# Site settings
title: 少逸博客             # title of your website
SEOTitle: 少逸博客     # check out docs for more detail
description: "少逸博客"    # ...

# SNS settings      
github_username: shaoyi52     # modify this account to yours
weibo_username: shaoyi52      # the footer woule be auto-updated.

# Build settings
# paginate: 10              # nums of posts in one page
# 
header-img: img/home-bg.jpg

# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value




# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "写写代码，做做设计，<br>离开世界之前，一切都是过程"
sidebar-avatar: /img/avatar-hux.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`


# Friends
friends: [
    {
    #     title: "Su",
    #     href: "http://su.gallery/"
    # },{
        title: "乱序",
        href: "http://mida.re/"
    },{
        title: "前端外刊评论",
        href: "http://qianduan.guru/"
    },{
        title: "天镶的博客",
        href: "http://lingyu.wang/"
    },{
        title: "Luke 的自留地",
        href: "http://hmqk1995.github.io"
    },{
        title: "Ebn's Blog",
        href: "http://ebnbin.com/"
    },{
        title: "SmdCn's Blog",
        href: "http://blog.smdcn.net"
    },{
        title: "David's Game",
        href: "https://www.ruoyaowu.com/"
    },{
        title: "DHong Say",
        href: "http://dhong.co"
    },{
        title: "尹峰以为",
        href: "http://ingf.github.io/"
    },{
        title: "解旻的博客",
        href: "http://xieminis.me/"
    }
]
