# Site settings
title: 少逸博客             # title of your website
SEOTitle: 少逸博客     # check out docs for more detail
description: "少逸博客"    # ...

# SNS settings      
github_username: shaoyi52     # modify this account to yours
weibo_username: shaoyi52      # the footer woule be auto-updated.

# Build settings
# paginate: 10              # nums of posts in one page